apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.adminSecretName }}
  namespace: {{ .Values.namespace }}
data:
  username: {{ .Values.credentials.adminUsername | b64enc }}
  password: {{ .Values.credentials.adminPassword | b64enc }}
type: Opaque