apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-git-generator
spec:
  generators:
    - git:
        repoURL: 'https://your.repo.url/your-repo.git'
        revision: HEAD
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/hdti-devops/gitops-2lb.git'
        targetRevision: HEAD
        path: 'apps/{{path.basename}}'
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      createNamespace: true