apiVersion: v2
name: ingress-nginx
description: A Helm chart for NGINX Ingress Controller, a Kubernetes ingress controller that uses NGINX as a reverse proxy and load balancer.
type: application
version: 0.1.0
appVersion: '1.0.0'
dependencies:
  - name: ingress-nginx
    version: 4.12.1
    repository: https://kubernetes.github.io/ingress-nginx