apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ingress-nginx-admission-secrets
  namespace: sonarqube
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ingress-nginx-admission-secrets-binding
  namespace: sonarqube
subjects:
  - kind: ServiceAccount
    name: sonarqube-ingress-nginx
    namespace: sonarqube
roleRef:
  kind: Role
  name: ingress-nginx-admission-secrets
  apiGroup: rbac.authorization.k8s.io