apiVersion: batch/v1
kind: Job
metadata:
  name: ingress-nginx-admission-create
  namespace: sonarqube
  labels:
    app.kubernetes.io/name: sonarqube-ingress-nginx
    app.kubernetes.io/component: sonarqube-admission-webhook
spec:
  template:
    spec:
      serviceAccountName: sonarqube-ingress-nginx
      containers:
        - name: create
          image: registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.5.2
          args:
            - create
            - --host=sonarqube-ingress-nginx-controller-admission,sonarqube-ingress-nginx-controller-admission.sonarqube.svc
            - --namespace=sonarqube
            - --secret-name=sonarqube-ingress-nginx-admission
      restartPolicy: OnFailure
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"