apiVersion: v2
name: argo-cd
description: A Helm chart for Argo CD, a declarative, GitOps continuous delivery tool
type: application
version: 0.1.0
appVersion: '1.0.0'
dependencies:
  - name: argo-cd
    version: 6.10.2
    repository: https://argoproj.github.io/argo-helm